name: wlasl-classification
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn
  - opencv
  - torchvision
  - pytorch
  - cudatoolkit=10.2
  - pillow
  - pathlib

  # dev
  - flake8
  - black

  - pip
  - pip:
    - ramp-workflow
